In [1]:
import pandas as pd
import os

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
df = pd.read_parquet(os.path.join(os.getcwd(),'data','pre_normalized.parquet'))

In [4]:
df

,date,close,high,low,open,volume,tic,group_id,day,month,dayofweek,ema_50,ema_100,ema_200,rsi_14,stochrsi_14,macd,macd_signal,macd_hist,CDL2CROWS,CDL3BLACKCROWS,CDL3INSIDE,CDL3LINESTRIKE,CDL3OUTSIDE,CDL3STARSINSOUTH,CDL3WHITESOLDIERS,CDLABANDONEDBABY,CDLADVANCEBLOCK,CDLBELTHOLD,CDLBREAKAWAY,CDLCLOSINGMARUBOZU,CDLCONCEALBABYSWALL,CDLCOUNTERATTACK,CDLDARKCLOUDCOVER,CDLDOJI,CDLDOJISTAR,CDLDRAGONFLYDOJI,CDLENGULFING,CDLEVENINGDOJISTAR,CDLEVENINGSTAR,CDLGAPSIDESIDEWHITE,CDLGRAVESTONEDOJI,CDLHAMMER,CDLHANGINGMAN,CDLHARAMI,CDLHARAMICROSS,CDLHIGHWAVE,CDLHIKKAKE,CDLHIKKAKEMOD,CDLHOMINGPIGEON,CDLIDENTICAL3CROWS,CDLINNECK,CDLINVERTEDHAMMER,CDLKICKING,CDLKICKINGBYLENGTH,CDLLADDERBOTTOM,CDLLONGLEGGEDDOJI,CDLLONGLINE,CDLMARUBOZU,CDLMATCHINGLOW,CDLMATHOLD,CDLMORNINGDOJISTAR,CDLMORNINGSTAR,CDLONNECK,CDLPIERCING,CDLRICKSHAWMAN,CDLRISEFALL3METHODS,CDLSEPARATINGLINES,CDLSHOOTINGSTAR,CDLSHORTLINE,CDLSPINNINGTOP,CDLSTALLEDPATTERN,CDLSTICKSANDWICH,CDLTAKURI,CDLTASUKIGAP,CDLTHRUSTING,CDLTRISTAR,CDLUNIQUE3RIVER,CDLUPSIDEGAP2CROWS,CDLXSIDEGAP3METHODS,group,vix,Gold,Copper,Corn,Soybeans,Cocoa,Silver,bondyield,target,tic_id
0,2000-01-03,0.839281,0.843498,0.762429,0.786328,535796800,AAPL,0,3,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,24.675000,NaN,NaN,NaN,NaN,834.00,NaN,6.523333,-0.853105,0
1,2000-01-04,0.768521,0.829440,0.758680,0.811633,512377600,AAPL,0,4,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,25.982500,NaN,NaN,NaN,NaN,832.50,NaN,6.440000,-0.740336,0
2,2000-01-05,0.779767,0.828971,0.772269,0.777892,778321600,AAPL,0,5,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,27.310000,NaN,NaN,NaN,NaN,837.25,NaN,6.546667,-0.924126,0
3,2000-01-06,0.712287,0.802260,0.712287,0.795700,767972800,AAPL,0,6,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,25.955000,NaN,NaN,NaN,NaN,835.50,NaN,6.500000,0.182153,0
4,2000-01-07,0.746027,0.757274,0.716037,0.723534,460734400,AAPL,0,7,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,23.437500,NaN,NaN,NaN,NaN,848.00,NaN,6.460000,0.093936,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180266,2025-12-18,114.830002,116.480003,114.610001,115.010002,21476700,WMT,0,18,12,3,108.215177,104.684291,99.535772,0.620639,0.000000,2.926659,2.893111,0.033548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,17.022501,4336.700073,5.349125,442.8750,1055.6875,5942.25,65.105501,4.126667,-0.262781,28
180267,2025-12-19,114.360001,115.279999,113.529999,115.139999,50043800,WMT,0,19,12,4,108.456151,104.875889,99.683277,0.602508,0.000000,2.726061,2.859701,-0.133640,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,15.665000,4355.750000,5.441125,443.7500,1050.6250,5886.25,66.667501,4.153333,-0.158669,28
180268,2025-12-22,112.599998,114.320000,112.220001,114.010002,21473900,WMT,0,22,12,0,108.618655,105.028842,99.811801,0.539006,0.000000,2.397433,2.767247,-0.369814,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,14.632500,4408.600098,5.444625,445.2500,1051.5625,5864.25,67.695248,4.150000,-0.060317,28
180269,2025-12-23,110.900002,112.349998,110.699997,111.989998,20319900,WMT,0,23,12,1,108.708119,105.145103,99.922132,0.485751,0.000000,1.977027,2.609203,-0.632176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,14.045000,4485.074829,5.464875,447.3125,1053.1250,5892.25,69.803749,4.163333,0.045955,28
180270,2025-12-24,111.610001,111.709999,110.550003,110.900002,9009600,WMT,0,24,12,2,108.821919,105.273120,100.038429,0.507631,0.085965,1.681757,2.423714,-0.741957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Unknown,13.775000,4488.275024,5.508125,449.0000,1057.5000,5948.00,71.265249,4.136667,0.102674,28

In [5]:
df_norm = pd.read_parquet(os.path.join(os.getcwd(),'data','normalized_data.parquet'))

In [13]:
df_norm['target'].max()

136.66661485706038

In [15]:
len(df_norm.index)

316798

In [6]:
df_norm.head()

,close,high,low,open,volume,group_id,day,month,dayofweek,ema_50,ema_100,ema_200,rsi_14,stochrsi_14,macd,macd_signal,macd_hist,CDL2CROWS,CDL3BLACKCROWS,CDL3INSIDE,CDL3LINESTRIKE,CDL3OUTSIDE,CDL3STARSINSOUTH,CDL3WHITESOLDIERS,CDLABANDONEDBABY,CDLADVANCEBLOCK,CDLBELTHOLD,CDLBREAKAWAY,CDLCLOSINGMARUBOZU,CDLCONCEALBABYSWALL,CDLCOUNTERATTACK,CDLDARKCLOUDCOVER,CDLDOJI,CDLDOJISTAR,CDLDRAGONFLYDOJI,CDLENGULFING,CDLEVENINGDOJISTAR,CDLEVENINGSTAR,CDLGAPSIDESIDEWHITE,CDLGRAVESTONEDOJI,CDLHAMMER,CDLHANGINGMAN,CDLHARAMI,CDLHARAMICROSS,CDLHIGHWAVE,CDLHIKKAKE,CDLHIKKAKEMOD,CDLHOMINGPIGEON,CDLIDENTICAL3CROWS,CDLINNECK,CDLINVERTEDHAMMER,CDLKICKING,CDLKICKINGBYLENGTH,CDLLADDERBOTTOM,CDLLONGLEGGEDDOJI,CDLLONGLINE,CDLMARUBOZU,CDLMATCHINGLOW,CDLMATHOLD,CDLMORNINGDOJISTAR,CDLMORNINGSTAR,CDLONNECK,CDLPIERCING,CDLRICKSHAWMAN,CDLRISEFALL3METHODS,CDLSEPARATINGLINES,CDLSHOOTINGSTAR,CDLSHORTLINE,CDLSPINNINGTOP,CDLSTALLEDPATTERN,CDLSTICKSANDWICH,CDLTAKURI,CDLTASUKIGAP,CDLTHRUSTING,CDLTRISTAR,CDLUNIQUE3RIVER,CDLUPSIDEGAP2CROWS,CDLXSIDEGAP3METHODS,vix,Gold,Copper,Corn,Soybeans,Cocoa,Silver,bondyield,target,tic_id
0,1.023519,1.023634,0.995996,1.004505,20.099073,0,3,1,0,0.693147,0.693147,0.693147,0.693147,0.693147,3.937378,3.828825,3.053602,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,2.865624,0.693147,0.693147,0.693147,0.693147,6.728629,0.693147,2.142808,-0.853105,0
1,0.997764,1.018571,0.994610,1.013729,20.054371,0,4,1,1,0.693147,0.693147,0.693147,0.693147,0.693147,3.937378,3.828825,3.053602,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,2.937441,0.693147,0.693147,0.693147,0.693147,6.726833,0.693147,2.132982,-0.740336,0
2,1.001902,1.018401,0.999624,1.001410,20.472518,0,5,1,2,0.693147,0.693147,0.693147,0.693147,0.693147,3.937378,3.828825,3.053602,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,3.005435,0.693147,0.693147,0.693147,0.693147,6.732509,0.693147,2.145541,-0.924126,0
3,0.976813,1.008707,0.977302,1.007931,20.459130,0,6,1,3,0.693147,0.693147,0.693147,0.693147,0.693147,3.937378,3.828825,3.053602,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,2.935982,0.693147,0.693147,0.693147,0.693147,6.730421,0.693147,2.140066,0.182153,0
4,0.989436,0.992165,0.978712,0.981239,19.948108,0,7,1,4,0.693147,0.693147,0.693147,0.693147,0.693147,3.937378,3.828825,3.053602,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,2.792544,0.693147,0.693147,0.693147,0.693147,6.745236,0.693147,2.135349,0.093936,0

In [5]:
import yfinance as yf
import pandas as pd
import numpy as np

# Download stock data
df = yf.download(
    "AAPL",
    start="2022-01-01",
    end="2024-01-01",
    progress=False,
    multi_level_index= False
)

df = df.reset_index()

In [6]:
df

          Date       Close        High         Low        Open     Volume
0   2022-01-03  178.270325  179.122459  174.058687  174.176216  104487900
1   2022-01-04  176.007767  179.181201  175.439682  178.877573   99310400
2   2022-01-05  171.326004  176.468135  171.051758  175.919643   94537600
3   2022-01-06  168.466003  171.698203  168.113400  169.151618   96904000
4   2022-01-07  168.632492  170.562016  167.515916  169.337700   86709100
..         ...         ...         ...         ...         ...        ...
496 2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
497 2023-12-26  191.243896  192.076034  191.025954  191.798655   28919300
498 2023-12-27  191.342957  191.689688  189.302232  190.689143   48087700
499 2023-12-28  191.768936  192.838834  191.362768  192.323695   34049900
500 2023-12-29  190.728760  192.581260  189.936241  192.085938   42672100

[501 rows x 6 columns]

In [7]:
def add_fibonacci_features(df, window=60):
    df = df.copy()

    # Rolling swing high / low
    df["swing_high"] = df["High"].rolling(window).max()
    df["swing_low"] = df["Low"].rolling(window).min()

    # Price range
    df["range"] = df["swing_high"] - df["swing_low"]

    # Fibonacci retracement levels
    df["fib_38"] = df["swing_high"] - 0.382 * df["range"]
    df["fib_50"] = df["swing_high"] - 0.5 * df["range"]
    df["fib_61"] = df["swing_high"] - 0.618 * df["range"]

    # Normalized distance features (RNN-friendly)
    df["dist_fib_38"] = (df["Close"] - df["fib_38"]) / df["range"]
    df["dist_fib_50"] = (df["Close"] - df["fib_50"]) / df["range"]
    df["dist_fib_61"] = (df["Close"] - df["fib_61"]) / df["range"]

    # Break indicator
    df["break_fib_61"] = (df["Close"] < df["fib_61"]).astype(int)

    return df

In [8]:
df = add_fibonacci_features(df, window=60)

# Drop rows with NaN (caused by rolling window)
df = df.dropna().reset_index(drop=True)

In [9]:
df

,Date,Close,High,Low,Open,Volume,swing_high,swing_low,range,fib_38,fib_50,fib_61,dist_fib_38,dist_fib_50,dist_fib_61,break_fib_61
0,2022-03-29,175.506302,175.555325,172.936854,173.280106,100589400,179.181201,147.203272,31.977929,166.965632,163.192237,159.418841,0.267080,0.385080,0.503080,0
1,2022-03-30,174.339294,176.143781,173.289937,175.104240,92633200,179.181201,147.203272,31.977929,166.965632,163.192237,159.418841,0.230586,0.348586,0.466586,0
2,2022-03-31,171.240265,174.594262,171.034311,174.407926,103049300,176.468135,147.203272,29.264862,165.288957,161.835704,158.382450,0.203360,0.321360,0.439360,0
3,2022-04-01,170.946045,171.505052,168.621788,170.671450,78751300,176.143781,147.203272,28.940509,165.088507,161.673527,158.258547,0.202399,0.320399,0.438399,0
4,2022-04-04,174.996338,175.045376,171.073533,171.201029,76468400,176.143781,147.203272,28.940509,165.088507,161.673527,158.258547,0.342352,0.460352,0.578352,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,2023-12-22,191.788773,193.581837,191.164662,193.353978,37149600,197.752444,163.904132,33.848312,184.822389,180.828288,176.834188,0.205812,0.323812,0.441812,0
438,2023-12-26,191.243896,192.076034,191.025954,191.798655,28919300,197.752444,163.904132,33.848312,184.822389,180.828288,176.834188,0.189714,0.307714,0.425714,0
439,2023-12-27,191.342957,191.689688,189.302232,190.689143,48087700,197.752444,163.904132,33.848312,184.822389,180.828288,176.834188,0.192641,0.310641,0.428641,0
440,2023-12-28,191.768936,192.838834,191.362768,192.323695,34049900,197.752444,163.904132,33.848312,184.822389,180.828288,176.834188,0.205226,0.323226,0.441226,0
441,2023-12-29,190.728760,192.581260,189.936241,192.085938,42672100,197.752444,163.904132,33.848312,184.822389,180.828288,176.834188,0.174495,0.292495,0.410495,0