In [2]:
import pandas as pd
import os

In [7]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
df = pd.read_parquet(os.path.join(os.getcwd(),'data','test','pre_normalized.parquet'))

In [4]:
df

,date,close,high,low,open,volume,tic,day,month,dayofweek,...,Gold,Copper,Corn,Soybeans,Cocoa,Silver,bondyield,target,tic_id,group_id
0,2004-02-05,16.848316,17.012024,15.859245,16.200304,27565200,AIZ,5,2,3,...,398.824997,1.175125,271.5625,812.3125,1594.75,6.136250,3.726667,-0.080966,5,5
1,2004-02-06,16.950630,17.012021,16.473147,16.855133,5284400,AIZ,6,2,4,...,401.150002,1.175750,276.6250,837.0625,1566.75,6.277500,3.656667,-0.603600,5,5
2,2004-02-09,16.691425,16.848313,16.370830,16.780101,3252900,AIZ,9,2,0,...,405.474991,1.185000,277.6875,831.8750,1533.50,6.347500,3.636667,0.531270,5,5
3,2004-02-10,16.609571,16.691425,16.404935,16.473147,1651600,AIZ,10,2,1,...,407.874992,1.179250,283.0625,845.5000,1519.50,6.385000,3.676667,4.312109,5,5
4,2004-02-11,16.541363,16.711892,16.473151,16.561827,2010200,AIZ,11,2,2,...,409.000000,1.210000,280.8125,832.2500,1521.00,6.555000,3.613333,5.896854,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
628097,2025-12-17,236.740005,237.940002,234.529999,235.289993,2530100,UNP,17,12,2,...,4328.974976,5.340375,438.5000,1060.6875,6004.25,65.770498,4.160000,-0.713864,94,7
628098,2025-12-18,234.419998,238.009995,234.080002,236.800003,3053400,UNP,18,12,3,...,4336.700073,5.349125,442.8750,1055.6875,5942.25,65.105501,4.126667,-0.418051,94,7
628099,2025-12-19,234.229996,235.500000,232.039993,234.419998,4721900,UNP,19,12,4,...,4355.750000,5.441125,443.7500,1050.6250,5886.25,66.667501,4.153333,0.128081,94,7
628100,2025-12-22,234.610001,235.220001,232.509995,234.740005,2095600,UNP,22,12,0,...,4408.600098,5.444625,445.2500,1051.5625,5864.25,67.695248,4.150000,-0.660672,94,7
628101,2025-12-23,234.149994,235.229996,233.250000,234.679993,1980700,UNP,23,12,1,...,4485.074829,5.464875,447.3125,1053.1250,5892.25,69.803749,4.163333,-1.208621,94,7

In [5]:
df_norm = pd.read_parquet(os.path.join(os.getcwd(),'data','normalized_data.parquet'))

In [9]:
df_norm.head()

,date,close,high,low,open,volume,tic,day,month,dayofweek,ema_50,ema_100,ema_200,rsi_14,stochrsi_14,macd,macd_signal,macd_hist,CDL2CROWS,CDL3BLACKCROWS,CDL3INSIDE,CDL3LINESTRIKE,CDL3OUTSIDE,CDL3STARSINSOUTH,CDL3WHITESOLDIERS,CDLABANDONEDBABY,CDLADVANCEBLOCK,CDLBELTHOLD,CDLBREAKAWAY,CDLCLOSINGMARUBOZU,CDLCONCEALBABYSWALL,CDLCOUNTERATTACK,CDLDARKCLOUDCOVER,CDLDOJI,CDLDOJISTAR,CDLDRAGONFLYDOJI,CDLENGULFING,CDLEVENINGDOJISTAR,CDLEVENINGSTAR,CDLGAPSIDESIDEWHITE,CDLGRAVESTONEDOJI,CDLHAMMER,CDLHANGINGMAN,CDLHARAMI,CDLHARAMICROSS,CDLHIGHWAVE,CDLHIKKAKE,CDLHIKKAKEMOD,CDLHOMINGPIGEON,CDLIDENTICAL3CROWS,CDLINNECK,CDLINVERTEDHAMMER,CDLKICKING,CDLKICKINGBYLENGTH,CDLLADDERBOTTOM,CDLLONGLEGGEDDOJI,CDLLONGLINE,CDLMARUBOZU,CDLMATCHINGLOW,CDLMATHOLD,CDLMORNINGDOJISTAR,CDLMORNINGSTAR,CDLONNECK,CDLPIERCING,CDLRICKSHAWMAN,CDLRISEFALL3METHODS,CDLSEPARATINGLINES,CDLSHOOTINGSTAR,CDLSHORTLINE,CDLSPINNINGTOP,CDLSTALLEDPATTERN,CDLSTICKSANDWICH,CDLTAKURI,CDLTASUKIGAP,CDLTHRUSTING,CDLTRISTAR,CDLUNIQUE3RIVER,CDLUPSIDEGAP2CROWS,CDLXSIDEGAP3METHODS,group,vix,Gold,Copper,Corn,Soybeans,Cocoa,Silver,bondyield,target,tic_id,group_id
0,2004-02-05,2.934803,2.943465,2.881009,2.899777,17.132065,AIZ,5,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,Financial Services,2.369075,4.976734,0.943322,4.589422,5.981572,6.815914,1.413484,1.633154,-0.080977,2,2
1,2004-02-06,2.940225,2.943465,2.914857,2.935182,15.480270,AIZ,6,2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,Financial Services,2.274700,4.992641,0.943565,4.639572,6.042187,6.784740,1.447272,1.619388,-0.603623,2,2
2,2004-02-09,2.926431,2.934803,2.909295,2.931188,14.995058,AIZ,9,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,Financial Services,2.235644,5.021575,0.947159,4.649785,6.029783,6.746412,1.463603,1.615420,0.531235,2,2
3,2004-02-10,2.922035,2.926431,2.911152,2.914682,14.317256,AIZ,10,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,Financial Services,2.210744,5.037277,0.944927,4.699912,6.062039,6.729824,1.472243,1.623341,4.312119,2,2
4,2004-02-11,2.918357,2.927527,2.914857,2.919479,14.513746,AIZ,11,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,0.693147,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,0.693147,0.693147,0.693147,0.693147,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,1.098612,1.098612,1.098612,0.693147,0.693147,1.098612,1.098612,1.098612,0.693147,1.098612,1.098612,Financial Services,2.147392,5.044553,0.956809,4.679234,6.030685,6.731615,1.510501,1.610770,5.896876,2,2